language: python
python: 
 - "2.7"
 - "3.6"

install:
  - pip install -r requirements.txt
  - pip install ansible-lint

script:
  - ansible-playbook -vvv --syntax-check playbook.yml
  - ansible-lint -v playbook.yml
